In [ ]:
# Pandas

# Pandas (Python for Data Analysis) adalah library Python yang fokus untuk proses analisis data seperti manipulasi data, persiapan data, dan pembersihan data.

# read_csv() digunakan untuk membaca file csv
# str.match() digunakan untuk mencocokan dengan karakter tertentu
# drop() digunakan untuk menghapus
# count() digunakan untuk mengitung masing-masing variable
# drop_duplicates() digunakan untuk menghapus data duplicate rows
# fillna() digunakan untuk mengisi dengan nilai tertentu
# quantile() digunakan untuk melihat quantile ke tertentu
# mask() menganti nilai tertentu jika kondisi memenuhi
# astype() merunubah tipe data
# value_counts() digunakan untuk mengitung unik dari kolom
# sort_values() digunakan untuk sort values
# isnull() digunakan untuk mendeteksi missing values
# dropna() digunakan untuk menghapus missing values
# replace() digunakan untuk mengganti nilai
# Matplotlib

# Matplotlib adalah library Python yang fokus pada visualisasi data seperti membuat plot grafik. Matplotlib dapat digunakan dalam skrip Python, Python dan IPython shell, server aplikasi web, dan beberapa toolkit graphical user interface (GUI) lainnya.

# figure() digunakan untuk membuat figure gambar baru
# Seaborn

# Seaborn membangun di atas Matplotlib dan memperkenalkan tipe plot tambahan. Ini juga membuat plot Matplotlib tradisional Anda terlihat sedikit lebih cantik.

# box_plot() digunakan untuk membuat box plot

In [ ]:
# Untuk Dataset yang digunakan sudah disediakan dalam format csv, silahkan baca melalui fungsi pandas di python df_load = pd.read_csv('https://dqlab-dataset.s3-ap-southeast-1.amazonaws.com/dqlab_telco.csv')

 
# Untuk detil datanya adalah sebagai berikut:

# UpdatedAt Periode of Data taken
# customerID Customer ID
# gender Whether the customer is a male or a female (Male, Female)
# SeniorCitizen Whether the customer is a senior citizen or not (1, 0)
# Partner Whether the customer has a partner or not (Yes, No)
# Dependents Whether the customer has dependents or not (Yes, No)
# tenure Number of months the customer has stayed with the company
# PhoneService Whether the customer has a phone service or not (Yes, No)
# MultipleLines Whether the customer has multiple lines or not (Yes, No, No phone service)
# InternetService Customer’s internet service provider (DSL, Fiber optic, No)
# OnlineSecurity Whether the customer has online security or not (Yes, No, No internet service)
# OnlineBackup Whether the customer has online backup or not (Yes, No, No internet service)
# DeviceProtection Whether the customer has device protection or not (Yes, No, No internet service)
# TechSupport Whether the customer has tech support or not (Yes, No, No internet service)
# StreamingTV Whether the customer has streaming TV or not (Yes, No, No internet service)
# StreamingMovies Whether the customer has streaming movies or not (Yes, No, No internet service)
# Contract The contract term of the customer (Month-to-month, One year, Two year)
# PaperlessBilling Whether the customer has paperless billing or not (Yes, No)
# PaymentMethod The customer’s payment method (Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic))
# MonthlyCharges The amount charged to the customer monthly
# TotalCharges The total amount charged to the customer
# Churn Whether the customer churned or not (Yes or No)

In [37]:
#import library
import pandas as pd
pd.options.display.max_columns = 50

#import dataset
df_load = pd.read_csv('https://dqlab-dataset.s3-ap-southeast-1.amazonaws.com/dqlab_telco.csv')

#Tampilkan jumlah baris dan kolom
print(df_load.shape)

#Tampilkan 5 data teratas
print(df_load.head())

#Jumlah ID yang unik
print(df_load['customerID'].nunique())

(7113, 22)
   UpdatedAt   customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     202006  45759018157  Female              0     Yes         No     1.0
1     202006  45557574145    Male              0      No         No    34.0
2     202006  45366876421    Male              0      No         No     2.0
3     202006  45779536532    Male              0      No         No    45.0
4     202006  45923787906  Female              0      No         No     2.0

  PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup  \
0           No  No phone service             DSL             No          Yes
1          Yes                No             DSL            Yes           No
2          Yes                No             DSL            Yes          Yes
3           No  No phone service             DSL            Yes           No
4          Yes                No     Fiber optic             No           No

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month
1              Yes          No          No              No        One year
2               No          No          No              No  Month-to-month
3              Yes         Yes          No              No        One year
4               No          No          No              No  Month-to-month

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85
1               No               Mailed check           56.95       1889.50
2              Yes               Mailed check           53.85        108.15
3               No  Bank transfer (automatic)           42.30       1840.75
4              Yes           Electronic check           70.70        151.65

  Churn
0    No
1    No
2   Yes
3    No
4   Yes
7017

In [7]:
df_load.head()

,UpdatedAt,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7108,202006,45117219093,Male,0,Yes,Yes,53.0,Yes,Yes,DSL,Yes,Yes,No,No,No,Yes,Two year,No,Bank transfer (automatic),69.70,3686.05,NaN
7109,202006,45564915800,Female,0,No,No,12.0,Yes,No,Fiber optic,No,No,Yes,No,Yes,Yes,One year,No,Mailed check,95.50,1115.15,NaN
7110,202006,45655964195,Male,0,No,No,26.0,Yes,No,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,98.65,2537.00,NaN
7111,202006,45899251814,Male,0,No,No,21.0,Yes,No,DSL,No,No,Yes,No,No,Yes,Month-to-month,No,Mailed check,61.65,1393.60,NaN
7112,202006,45427332508,Female,0,No,Yes,1.0,Yes,No,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,89.35,89.35,NaN

In [35]:
df_load['customerID'].value_counts()

4.55E+11       18
4.59E+11       13
4.57E+11       12
4.54E+11       10
4.60E+11        9
               ..
45208031543     1
45350972776     1
45501692587     1
45816174300     1
45519372152     1
Name: customerID, Length: 7017, dtype: int64

In [38]:
#import library
import pandas as pd
pd.options.display.max_columns = 50

#import dataset
df_load = pd.read_csv('https://dqlab-dataset.s3-ap-southeast-1.amazonaws.com/dqlab_telco.csv')

#Tampilkan jumlah baris dan kolom
print(df_load.shape)

#Tampilkan 5 data teratas
print(df_load.head(5))

#Jumlah ID yang unik
print(df_load.customerID.nunique())

(7113, 22)
   UpdatedAt   customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     202006  45759018157  Female              0     Yes         No     1.0
1     202006  45557574145    Male              0      No         No    34.0
2     202006  45366876421    Male              0      No         No     2.0
3     202006  45779536532    Male              0      No         No    45.0
4     202006  45923787906  Female              0      No         No     2.0

  PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup  \
0           No  No phone service             DSL             No          Yes
1          Yes                No             DSL            Yes           No
2          Yes                No             DSL            Yes          Yes
3           No  No phone service             DSL            Yes           No
4          Yes                No     Fiber optic             No           No

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month
1              Yes          No          No              No        One year
2               No          No          No              No  Month-to-month
3              Yes         Yes          No              No        One year
4               No          No          No              No  Month-to-month

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85
1               No               Mailed check           56.95       1889.50
2              Yes               Mailed check           53.85        108.15
3               No  Bank transfer (automatic)           42.30       1840.75
4              Yes           Electronic check           70.70        151.65

  Churn
0    No
1    No
2   Yes
3    No
4   Yes
7017