In [5]:
import pandas as pd
# Load data global_air_quality.csv
global_air_quality = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/LO4/global_air_quality_4000rows.csv')
print('Lima data teratas:\n', global_air_quality.head())
# Melakukan pengecekan terhadap data
print('Info global_air_quality:\n', global_air_quality.info())
# Melakukan count tanpa groupby
print('Count tanpa groupby:\n', global_air_quality.count())
# Melakukan count dengan groupby 
gaq_groupby_count = global_air_quality.groupby('source_name').count()
print('Count dengan groupby (5 data teratas):\n', gaq_groupby_count.head())

Lima data teratas:
                           location       city country pollutant  value  \
0                  MOBILE-KICKAPOO    LINCOLN      US      pm10   7.00
1                  Oxford St Ebbes     Oxford      GB       no2  30.00
2                 BROADWAY (South)  St. Louis      US      pm25   6.10
3  Deen Dayal Nagar, Sagar - MPPCB      Sagar      IN      pm25  23.67
4                        Manglerud       Oslo      NO      pm10  27.06

                 timestamp   unit source_name   latitude  longitude  \
0  2017-01-18 16:00:00 UTC  µg/m³      AirNow  35.488400 -97.090280
1  2020-04-07 20:00:00 UTC  µg/m³       DEFRA  51.744804  -1.260278
2  2020-04-07 19:00:00 UTC  µg/m³      AirNow  38.542500 -90.263610
3  2020-04-07 18:30:00 UTC  µg/m³       caaqm  23.864016  78.802895
4  2020-04-07 20:00:00 UTC  µg/m³      Norway  59.898690  10.814950

   averaged_over_in_hours
0                    1.00
1                    1.00
2                    1.00
3                    0.25
4                    1.00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   location                3997 non-null   object
 1   city                    3966 non-null   object
 2   country                 4000 non-null   object
 3   pollutant               4000 non-null   object
 4   value                   4000 non-null   float64
 5   timestamp               4000 non-null   object
 6   unit                    4000 non-null   object
 7   source_name             4000 non-null   object
 8   latitude                4000 non-null   float64
 9   longitude               4000 non-null   float64
 10  averaged_over_in_hours  3634 non-null   float64
dtypes: float64(4), object(7)
memory usage: 343.9+ KB
Info global_air_quality:
 None
Count tanpa groupby:
 location                  3997
city                      3966
country                   4000
pollutant                 4000
value                     4000
timestamp                 4000
unit                      4000
source_name               4000
latitude                  4000
longitude                 4000
averaged_over_in_hours    3634
dtype: int64
Count dengan groupby (5 data teratas):
              location  city  country  pollutant  value  timestamp  unit  \
source_name
ARPALAZIO          72    72       72         72     72         72    72
Agaar.mn           27    27       27         27     27         27    27
AirNow           1712  1681     1715       1715   1715       1715  1715
Andalucia          71    71       71         71     71         71    71
Anqing              4     4        4          4      4          4     4

             latitude  longitude  averaged_over_in_hours
source_name
ARPALAZIO          72         72                      72
Agaar.mn           27         27                       0
AirNow           1715       1715                    1715
Andalucia          71         71                      71
Anqing              4          4                       4

In [1]:
import pandas as pd
# Load data global_air_quality.csv
global_air_quality = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/LO4/global_air_quality_4000rows.csv')
print('Lima data teratas:\n', global_air_quality.head())

Lima data teratas:
                           location       city country pollutant  value  \
0                  MOBILE-KICKAPOO    LINCOLN      US      pm10   7.00
1                  Oxford St Ebbes     Oxford      GB       no2  30.00
2                 BROADWAY (South)  St. Louis      US      pm25   6.10
3  Deen Dayal Nagar, Sagar - MPPCB      Sagar      IN      pm25  23.67
4                        Manglerud       Oslo      NO      pm10  27.06

                 timestamp   unit source_name   latitude  longitude  \
0  2017-01-18 16:00:00 UTC  µg/m³      AirNow  35.488400 -97.090280
1  2020-04-07 20:00:00 UTC  µg/m³       DEFRA  51.744804  -1.260278
2  2020-04-07 19:00:00 UTC  µg/m³      AirNow  38.542500 -90.263610
3  2020-04-07 18:30:00 UTC  µg/m³       caaqm  23.864016  78.802895
4  2020-04-07 20:00:00 UTC  µg/m³      Norway  59.898690  10.814950

   averaged_over_in_hours
0                    1.00
1                    1.00
2                    1.00
3                    0.25
4                    1.00

In [2]:
global_air_quality

,location,city,country,pollutant,value,timestamp,unit,source_name,latitude,longitude,averaged_over_in_hours
0,MOBILE-KICKAPOO,LINCOLN,US,pm10,7.000,2017-01-18 16:00:00 UTC,µg/m³,AirNow,35.488400,-97.090280,1.00
1,Oxford St Ebbes,Oxford,GB,no2,30.000,2020-04-07 20:00:00 UTC,µg/m³,DEFRA,51.744804,-1.260278,1.00
2,BROADWAY (South),St. Louis,US,pm25,6.100,2020-04-07 19:00:00 UTC,µg/m³,AirNow,38.542500,-90.263610,1.00
3,"Deen Dayal Nagar, Sagar - MPPCB",Sagar,IN,pm25,23.670,2020-04-07 18:30:00 UTC,µg/m³,caaqm,23.864016,78.802895,0.25
4,Manglerud,Oslo,NO,pm10,27.060,2020-04-07 20:00:00 UTC,µg/m³,Norway,59.898690,10.814950,1.00
...,...,...,...,...,...,...,...,...,...,...,...
3995,SPRINGHILL,Knoxville,US,o3,0.046,2020-04-07 19:00:00 UTC,ppm,AirNow,36.018300,-83.876100,1.00
3996,Central Phoenix,Phoenix-Mesa-Scottsdale,US,co,0.400,2020-04-07 19:00:00 UTC,ppm,AirNow,33.457900,-112.046000,1.00
3997,Mobile-Wyandotte,OTTAWA,US,pm10,6.000,2018-10-18 14:00:00 UTC,µg/m³,AirNow,36.804670,-94.725020,1.00
3998,"New Industrial Town, Faridabad - HSPCB",Faridabad,IN,co,1310.000,2020-04-02 06:15:00 UTC,µg/m³,caaqm,28.390720,77.300590,0.25
3999,Reja,Płock,PL,pm10,134.000,2017-01-08 08:00:00 UTC,µg/m³,Poland,52.550940,19.705278,1.00