In [1]:
import pandas as pd

In [15]:
data = pd.read_csv('Global_Mobility_Report.csv', low_memory=False)

In [19]:
databaru = data[data['country_region']=='Indonesia']

In [28]:
databaru['sub_region_1'].unique()

array([nan, 'Aceh', 'Bali', 'Bangka Belitung Islands', 'Banten',
       'Bengkulu', 'Central Java', 'Central Kalimantan',
       'Central Sulawesi', 'East Java', 'East Kalimantan',
       'East Nusa Tenggara', 'Gorontalo', 'Jakarta', 'Jambi', 'Lampung',
       'Maluku', 'North Kalimantan', 'North Maluku', 'North Sulawesi',
       'North Sumatra', 'Papua', 'Riau', 'Riau Islands',
       'South East Sulawesi', 'South Kalimantan', 'South Sulawesi',
       'South Sumatra', 'Special Region of Yogyakarta', 'West Java',
       'West Kalimantan', 'West Nusa Tenggara', 'West Papua',
       'West Sulawesi', 'West Sumatra'], dtype=object)

In [54]:
data3

,country_region_code,country_region,sub_region_1,iso_3166_2_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
1712211,ID,Indonesia,NaN,NaN,2020-02-15,-2.0,-2.0,-8.0,1.0,5.0,1.0
1712212,ID,Indonesia,NaN,NaN,2020-02-16,-3.0,-3.0,-7.0,-4.0,2.0,2.0
1712213,ID,Indonesia,NaN,NaN,2020-02-17,-3.0,-4.0,-7.0,-1.0,3.0,1.0
1712214,ID,Indonesia,NaN,NaN,2020-02-18,-3.0,-2.0,-4.0,1.0,2.0,1.0
1712215,ID,Indonesia,NaN,NaN,2020-02-19,-3.0,-4.0,-3.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1724526,ID,Indonesia,West Sumatra,ID-SB,2021-01-27,-19.0,2.0,-29.0,-32.0,-24.0,8.0
1724527,ID,Indonesia,West Sumatra,ID-SB,2021-01-28,-12.0,10.0,-21.0,-28.0,-24.0,6.0
1724528,ID,Indonesia,West Sumatra,ID-SB,2021-01-29,-16.0,6.0,-29.0,-32.0,-22.0,6.0
1724529,ID,Indonesia,West Sumatra,ID-SB,2021-01-30,-18.0,4.0,-28.0,-33.0,-21.0,4.0
1724530,ID,Indonesia,West Sumatra,ID-SB,2021-01-31,-15.0,11.0,-22.0,-34.0,-9.0,3.0

In [53]:
data3 = data2.drop(columns='census_fips_code')

In [52]:
data1['census_fips_code'].isnull().sum()

12320

In [56]:
data3.isnull().sum()

country_region_code                                     0
country_region                                          0
sub_region_1                                          352
iso_3166_2_code                                       352
date                                                    0
retail_and_recreation_percent_change_from_baseline     50
grocery_and_pharmacy_percent_change_from_baseline      99
parks_percent_change_from_baseline                    118
transit_stations_percent_change_from_baseline         404
workplaces_percent_change_from_baseline                 0
residential_percent_change_from_baseline                0
dtype: int64

In [64]:
data3 = data3.reset_index(drop=True)

In [65]:
data3.to_csv('Covid Indonesia.csv')

In [66]:
dataset = pd.read_csv('Covid Indonesia.csv')

In [69]:
dataset.isnull().sum()

Unnamed: 0                                              0
country_region_code                                     0
country_region                                          0
sub_region_1                                          352
iso_3166_2_code                                       352
date                                                    0
retail_and_recreation_percent_change_from_baseline     50
grocery_and_pharmacy_percent_change_from_baseline      99
parks_percent_change_from_baseline                    118
transit_stations_percent_change_from_baseline         404
workplaces_percent_change_from_baseline                 0
residential_percent_change_from_baseline                0
dtype: int64

In [71]:
dataset = dataset.drop(columns='Unnamed: 0')

In [79]:
dataset.groupby(dataset['sub_region_1']).sum()

,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
sub_region_1,,,,,,
Aceh,-3606.0,432.0,-4402.0,-9331.0,-5418.0,1232.0
Bali,-12270.0,-8908.0,-14744.0,-21305.0,-12226.0,4746.0
Bangka Belitung Islands,-7374.0,-356.0,-3458.0,-12371.0,-6215.0,2262.0
Banten,-5996.0,-2011.0,-881.0,-15568.0,-7956.0,4572.0
Bengkulu,-3120.0,1130.0,-3889.0,-9403.0,-6416.0,2209.0
Central Java,-4133.0,-643.0,-5145.0,-10891.0,-6609.0,3695.0
Central Kalimantan,-6157.0,-1796.0,-6216.0,-6837.0,-6034.0,2023.0
Central Sulawesi,-4062.0,-117.0,305.0,-10039.0,-5200.0,2251.0
East Java,-5661.0,-1344.0,-6186.0,-11990.0,-6979.0,3685.0
East Kalimantan,-6761.0,-732.0,-4884.0,-11485.0,-6332.0,2856.0
East Nusa Tenggara,-4351.0,69.0,-110.0,-5756.0,-4014.0,1883.0
Gorontalo,-3038.0,-622.0,5193.0,-5569.0,-5806.0,2986.0
Jakarta,-12029.0,-4461.0,-19976.0,-15131.0,-10683.0,4944.0
Jambi,-5613.0,-157.0,-4304.0,-10191.0,-6033.0,2521.0
Lampung,-4125.0,1823.0,-3986.0,-9593.0,-7198.0,3081.0
Maluku,-7704.0,-2271.0,-2204.0,-10254.0,-7732.0,1902.0
North Kalimantan,-5487.0,973.0,-3932.0,-8867.0,-5518.0,1735.0
North Maluku,-5752.0,4484.0,-3853.0,-8325.0,-6191.0,1356.0
North Sulawesi,-8382.0,-1891.0,-5575.0,-10557.0,-6695.0,3390.0
North Sumatra,-7257.0,-2215.0,-5021.0,-10571.0,-7419.0,3256.0
Papua,-7572.0,-3642.0,-2779.0,-8694.0,-6202.0,2039.0
Riau,-5232.0,-1707.0,-2114.0,-12572.0,-6368.0,2762.0
Riau Islands,-8455.0,-3995.0,-7114.0,-18236.0,-6424.0,3293.0
South East Sulawesi,-4281.0,1154.0,-2423.0,-7141.0,-5202.0,2572.0
South Kalimantan,-5912.0,-1931.0,-5000.0,-11386.0,-6706.0,3218.0
South Sulawesi,-7118.0,-692.0,-2055.0,-14110.0,-8072.0,3570.0
South Sumatra,-6406.0,-1175.0,-1223.0,-12397.0,-6984.0,3060.0
Special Region of Yogyakarta,-8746.0,-5461.0,-11617.0,-17944.0,-8929.0,4209.0
West Java,-8387.0,30.0,-2363.0,-10465.0,-7835.0,4383.0
West Kalimantan,-8922.0,-3446.0,-5714.0,-12550.0,-6961.0,2690.0
West Nusa Tenggara,-5772.0,-1265.0,-6170.0,-13353.0,-5976.0,2747.0
West Papua,-6566.0,-1039.0,-9603.0,-12568.0,-7058.0,2241.0
West Sulawesi,-3637.0,855.0,-3828.0,-8160.0,-5398.0,2462.0
West Sumatra,-5044.0,1035.0,-5110.0,-10497.0,-7186.0,2957.0

In [77]:
dataset['sub_region_1']

0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
             ...
12315    West Sumatra
12316    West Sumatra
12317    West Sumatra
12318    West Sumatra
12319    West Sumatra
Name: sub_region_1, Length: 12320, dtype: object